### ISSUE TITLE
Enhancement suggestion: Search all dictionaries listed in plover.cfg

### ISSUE THREAD

**Issue by jeremy-w** [Achim63/plover-lookup-enhanced#1]
I hacked together my own version of this script prior to finding yours. I had my custom dictionaries in Dropbox, so I included support for dictionaries elsewhere to begin with:

``` fish
function plup --description 'Searches for words in all configured Plover dictionaries.'
    set -l config "$HOME/Library/Application Support/plover/plover.cfg"
    set -l dict_files (awk 'BEGIN{FS=" = "} /^dictionary_file/{print($2)}' $config)
    for word in $argv
        egrep -i $word -- $dict_files
    end
end
```

This function does assume the default Plover config file location is in force, but from that, it parses out the dictionary file paths, then iterates them running the search across each. Similar code should work for `dictlookup`, too. (If anything looks weird to you in that code, it's because I use Fish shell rather than Bash. :) )

**Comment by Achim63** [comment]
Thank you for the suggestion. Since I'm no good in bash scripting, I made a new Python script that also uses the dictionaries defined in plover.cfg. OSX only for now, but should be easily adaptable for Win and Linux (path to plover.cfg has to be changed accordingly).
